---
# The service account, cluster roles, and cluster role binding are
# only needed for Kubernetes with role-based access control (RBAC).
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: flux
  name: flux
  namespace: ladev
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    name: flux
  name: flux
  namespace: ladev
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    name: flux
  name: flux
  namespace: ladev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: ladev
