apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-kubeconfig
  namespace: ladev
data:
  config: |
    apiVersion: v1
    clusters: []
    contexts:
    - context:
        cluster: ""
        namespace: ladev
        user: ""
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users: []
